plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

tasks.withType(AbstractArchiveTask).configureEach {
    archiveVersion = "${project.mod_version}+mc${project.minecraft_version}"
}

repositories {
    mavenCentral()
    maven { url = uri("https://maven.puffish.net") }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation "net.puffish:attributesmod:0.8.2+26.1:fabric"

    compileOnly "mezz.jei:jei-${jei_minecraft_version}-fabric-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${jei_minecraft_version}-fabric:${jei_version}"

    testImplementation "org.junit.jupiter:junit-jupiter:5.10.0"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
}

fabricApi {
    configureTests {
        createSourceSet = true
        modId = "ascensioncores-gametest"
        enableGameTests = true
        enableClientGameTests = false
        eula = true
    }
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from('LICENSE') { rename { "${it}_${project.base.archivesName.get()}" } }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_dependency', project.minecraft_dependency
    filteringCharset 'UTF-8'
    filesMatching('fabric.mod.json') {
        expand 'version': project.version,
            'minecraft_dependency': project.minecraft_dependency
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}
